spring:
  application:
    name: inventory-service
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://psql:5432/inventory_db}
    username: ${DATABASE_USER:postgre_user}
    password: ${DATABASE_PASSWORD:postgre_secret_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: update
      format_sql: true
    show-sql: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    inventory-service-topic: inventory
    error-inventory-service-topic: inventory-error
    delivery-service-topic: delivery
    order-service-topic: order
    error-payment-service-topic: payment-error

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
    metrics:
      enabled: true

eureka:
  client:
    enabled: true